import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FloatingButton from "./components/FloatingButton";
const inter = Inter({ subsets: ["latin"] });
import {Providers} from "./Providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>
        <Header />
        <div className="items-center justify-center p-24 flex place-items-center ">

          {children}
        </div>{" "}
          </Providers>
        {/* <FloatingButton /> */}
      </body>
    </html>
  );
}
