import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FloatingButton from "./components/FloatingButton";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
import {Providers} from "./Providers";
export const metadata = {
  title: "Convive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>
        <Header />
        <div className="flex items-center justify-center p-12 sm:p-24">

          {children}
        </div>
        <Footer/>{" "}
          </Providers>
 
      </body>
   
    </html>
  );
}
